fmod BIBLIOTECA is
  protecting NAT .
  protecting STRING .

  --- 1. Sorts Básicos
  sorts Livro Usuario EstadoLivro .

  --- 2. Sorts de Coleções e Estado do Sistema
  sorts ConjuntoLivros ConjuntoUsuarios Emprestimo ConjuntoEmprestimos Sistema .

  --- 3. Construtores de Estados e Entidades Básicas
  ops disponivel emprestado : -> EstadoLivro [ctor] .
  op livro : Nat String EstadoLivro -> Livro [ctor] .
  op usuario : Nat String -> Usuario [ctor] .

  --- 4. Construtores de Coleções (Conjuntos)
  --- Elementos vazios
  op nenhumLivro : -> ConjuntoLivros [ctor] .
  op nenhumUsuario : -> ConjuntoUsuarios [ctor] .
  op nenhumEmprestimo : -> ConjuntoEmprestimos [ctor] .

  --- Subsorts: um Livro individual também é um ConjuntoLivros de tamanho 1, etc.
  subsort Livro < ConjuntoLivros .
  subsort Usuario < ConjuntoUsuarios .
  subsort Emprestimo < ConjuntoEmprestimos .

  --- União de conjuntos (usando espaço como operador transparente)
  op __ : ConjuntoLivros ConjuntoLivros -> ConjuntoLivros [ctor assoc comm id: nenhumLivro] .
  op __ : ConjuntoUsuarios ConjuntoUsuarios -> ConjuntoUsuarios [ctor assoc comm id: nenhumUsuario] .
  op __ : ConjuntoEmprestimos ConjuntoEmprestimos -> ConjuntoEmprestimos [ctor assoc comm id: nenhumEmprestimo] .

  --- 5. Construtor de Empréstimo (Relaciona ID do Livro com ID do Usuário)
  op emprestimo : Nat Nat -> Emprestimo [ctor] .

  --- 6. Construtor da Estrutura Global do Sistema
  --- sistema(Acervo, Usuarios, Emprestimos)
  op sistema : ConjuntoLivros ConjuntoUsuarios ConjuntoEmprestimos -> Sistema [ctor] .

endfm